In [1]:
!pip install numpy pandas matplotlib seaborn scikit-learn

Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.5)
Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.10.1)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn) (1.15.2)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ------ --------------------------------- 1.6/10.0 MB 7.7 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/10.0 MB 9.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/10.0 MB 10.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.9/10.0 MB 10.7 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 10.7 MB/s  0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ------------ --------------------------- 2.6/8.3 MB 12.5 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.3 MB 12.1 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.3 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 10.5 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, narwhals, joblib, scikit-learn, pandas, seaborn

   ---------------------------------------- 0/7 [tzdata]
   ----- ---------------------------------- 1/7 [threadpoolctl]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------- ---------------------------- 2/7 [narwhals]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ----------------- ---------------------- 3/7 [joblib]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------- ----------------- 4/7 [scikit-learn]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------- ----------- 5/7 [pandas]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------------- 7/7 [seaborn]

Successfully installed joblib-1.5.3 narwhals-2.24.0 pandas-3.0.5 scikit-learn-1.9.0 seaborn-0.13.2 threadpoolctl-3.6.0 tzdata-2026.3

[notice] A new release of pip is available: 25.2 -> 26.2
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = sns.load_dataset("titanic") # Titanic dataset
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None
         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [14]:
# 1. Fill missing ages (Modern approach)
df["age"] = df["age"].fillna(df["age"].median())

# 2. Fill missing embark towns (Modern approach)
df["embark_town"] = df["embark_town"].fillna(df["embark_town"].mode()[0])

# 3. Drop the deck column (Added errors="ignore" to prevent crashes if run twice)
df = df.drop(columns=["deck"], errors="ignore")

In [16]:
le = LabelEncoder()
df["sex"] = le.fit_transform(df["sex"])
df["embark_town"] = le.fit_transform(df["embark_town"])

# Drop non-informative or redundant columns
df.drop(columns=["embarked", "class", "who", "alive", "adult_male", "alone"], inplace=True)

In [17]:
scaler = StandardScaler()
numerical_cols = ["age", "fare"]
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [18]:
X = df.drop("survived", axis=1)
y = df["survived"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
print("Training Data Shape:", X_train.shape)
print("Test Data Shape:", X_test.shape)
X_train.head()

Training Data Shape: (712, 7)
Test Data Shape: (179, 7)

     pclass  sex       age  sibsp  parch      fare  embark_town
331       1    1  1.240235      0      0 -0.074583            2
733       2    1 -0.488887      0      0 -0.386671            2
382       3    1  0.202762      0      0 -0.488854            2
704       3    1 -0.258337      1      0 -0.490280            2
813       3    0 -1.795334      4      2 -0.018709            2